// flow-typed signature: 5b79cd04ad0eda0705f946d57abec323
// flow-typed version: <<STUB>>/babel-merge_v^2.0.1/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-merge'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-merge' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-merge/dist/index' {
  declare module.exports: any;
}

declare module 'babel-merge/src/index' {
  declare module.exports: any;
}

declare module 'babel-merge/test/index.test' {
  declare module.exports: any;
}

declare module 'babel-merge/test/local-plugin' {
  declare module.exports: any;
}

declare module 'babel-merge/test/local-preset' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-merge/dist/index.js' {
  declare module.exports: $Exports<'babel-merge/dist/index'>;
}
declare module 'babel-merge/src/index.js' {
  declare module.exports: $Exports<'babel-merge/src/index'>;
}
declare module 'babel-merge/test/index.test.js' {
  declare module.exports: $Exports<'babel-merge/test/index.test'>;
}
declare module 'babel-merge/test/local-plugin.js' {
  declare module.exports: $Exports<'babel-merge/test/local-plugin'>;
}
declare module 'babel-merge/test/local-preset.js' {
  declare module.exports: $Exports<'babel-merge/test/local-preset'>;
}
