// flow-typed signature: a506a40ec257e6438aa037f85813ece6
// flow-typed version: <<STUB>>/clean-webpack-plugin_v^0.1.19/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'clean-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'clean-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'clean-webpack-plugin/index' {
  declare module.exports: $Exports<'clean-webpack-plugin'>;
}
declare module 'clean-webpack-plugin/index.js' {
  declare module.exports: $Exports<'clean-webpack-plugin'>;
}
