// flow-typed signature: 177a5d6ad9c805fb7077d39a6526ae89
// flow-typed version: <<STUB>>/cloc_v^2.4.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cloc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cloc' {
  declare module.exports: any;
}
