// flow-typed signature: 15dd22c8fb59ec0c8dfa00b455062a2c
// flow-typed version: <<STUB>>/concurrently_v^3.6.1/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'concurrently'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'concurrently' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'concurrently/src/findChild' {
  declare module.exports: any;
}

declare module 'concurrently/src/main' {
  declare module.exports: any;
}

declare module 'concurrently/src/parseCmds' {
  declare module.exports: any;
}

declare module 'concurrently/src/pkgInfo' {
  declare module.exports: any;
}

declare module 'concurrently/test/support/read-echo' {
  declare module.exports: any;
}

declare module 'concurrently/test/support/signal' {
  declare module.exports: any;
}

declare module 'concurrently/test/test-findChild' {
  declare module.exports: any;
}

declare module 'concurrently/test/test-functional' {
  declare module.exports: any;
}

declare module 'concurrently/test/test-parseCmds' {
  declare module.exports: any;
}

declare module 'concurrently/test/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'concurrently/src/findChild.js' {
  declare module.exports: $Exports<'concurrently/src/findChild'>;
}
declare module 'concurrently/src/main.js' {
  declare module.exports: $Exports<'concurrently/src/main'>;
}
declare module 'concurrently/src/parseCmds.js' {
  declare module.exports: $Exports<'concurrently/src/parseCmds'>;
}
declare module 'concurrently/src/pkgInfo.js' {
  declare module.exports: $Exports<'concurrently/src/pkgInfo'>;
}
declare module 'concurrently/test/support/read-echo.js' {
  declare module.exports: $Exports<'concurrently/test/support/read-echo'>;
}
declare module 'concurrently/test/support/signal.js' {
  declare module.exports: $Exports<'concurrently/test/support/signal'>;
}
declare module 'concurrently/test/test-findChild.js' {
  declare module.exports: $Exports<'concurrently/test/test-findChild'>;
}
declare module 'concurrently/test/test-functional.js' {
  declare module.exports: $Exports<'concurrently/test/test-functional'>;
}
declare module 'concurrently/test/test-parseCmds.js' {
  declare module.exports: $Exports<'concurrently/test/test-parseCmds'>;
}
declare module 'concurrently/test/utils.js' {
  declare module.exports: $Exports<'concurrently/test/utils'>;
}
