// flow-typed signature: d1cc78ad7ebc6d774b3ace5c086ae344
// flow-typed version: <<STUB>>/kill-port_v^1.3.1/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'kill-port'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'kill-port' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'kill-port/cli' {
  declare module.exports: any;
}

declare module 'kill-port/example' {
  declare module.exports: any;
}

declare module 'kill-port/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'kill-port/cli.js' {
  declare module.exports: $Exports<'kill-port/cli'>;
}
declare module 'kill-port/example.js' {
  declare module.exports: $Exports<'kill-port/example'>;
}
declare module 'kill-port/index' {
  declare module.exports: $Exports<'kill-port'>;
}
declare module 'kill-port/index.js' {
  declare module.exports: $Exports<'kill-port'>;
}
declare module 'kill-port/test.js' {
  declare module.exports: $Exports<'kill-port/test'>;
}
