// flow-typed signature: 158dde30d64df8a31d55b61ed25f61bc
// flow-typed version: <<STUB>>/ospath_v^1.2.2/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ospath'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ospath' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'ospath/index' {
  declare module.exports: $Exports<'ospath'>;
}
declare module 'ospath/index.js' {
  declare module.exports: $Exports<'ospath'>;
}
