// flow-typed signature: 2016742cb8342bc3dd61d863983ff498
// flow-typed version: <<STUB>>/ps-tree_v^1.2.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ps-tree'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ps-tree' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ps-tree/bin/ps-tree' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ps-tree/bin/ps-tree.js' {
  declare module.exports: $Exports<'ps-tree/bin/ps-tree'>;
}
declare module 'ps-tree/index' {
  declare module.exports: $Exports<'ps-tree'>;
}
declare module 'ps-tree/index.js' {
  declare module.exports: $Exports<'ps-tree'>;
}
