// flow-typed signature: 3f18378830f11e65e94e0e3de0b6cfb0
// flow-typed version: <<STUB>>/react-ink_v^6.4.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-ink'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-ink' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-ink/dist/ink' {
  declare module.exports: any;
}

declare module 'react-ink/example/index' {
  declare module.exports: any;
}

declare module 'react-ink/src/index' {
  declare module.exports: any;
}

declare module 'react-ink/src/style' {
  declare module.exports: any;
}

declare module 'react-ink/src/util/easing' {
  declare module.exports: any;
}

declare module 'react-ink/src/util/equations' {
  declare module.exports: any;
}

declare module 'react-ink/src/util/hasTouch' {
  declare module.exports: any;
}

declare module 'react-ink/src/util/pixelRatio' {
  declare module.exports: any;
}

declare module 'react-ink/src/util/store' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-ink/dist/ink.js' {
  declare module.exports: $Exports<'react-ink/dist/ink'>;
}
declare module 'react-ink/example/index.js' {
  declare module.exports: $Exports<'react-ink/example/index'>;
}
declare module 'react-ink/src/index.js' {
  declare module.exports: $Exports<'react-ink/src/index'>;
}
declare module 'react-ink/src/style.js' {
  declare module.exports: $Exports<'react-ink/src/style'>;
}
declare module 'react-ink/src/util/easing.js' {
  declare module.exports: $Exports<'react-ink/src/util/easing'>;
}
declare module 'react-ink/src/util/equations.js' {
  declare module.exports: $Exports<'react-ink/src/util/equations'>;
}
declare module 'react-ink/src/util/hasTouch.js' {
  declare module.exports: $Exports<'react-ink/src/util/hasTouch'>;
}
declare module 'react-ink/src/util/pixelRatio.js' {
  declare module.exports: $Exports<'react-ink/src/util/pixelRatio'>;
}
declare module 'react-ink/src/util/store.js' {
  declare module.exports: $Exports<'react-ink/src/util/store'>;
}
