// flow-typed signature: c50d12a28db9385fc3cfbcb1a7f35657
// flow-typed version: <<STUB>>/react-focus-lock_v^1.17.7/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-focus-lock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-focus-lock' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-focus-lock/dist/cjs/AutoFocusInside' {
  declare module.exports: any;
}

declare module 'react-focus-lock/dist/cjs/FreeFocusInside' {
  declare module.exports: any;
}

declare module 'react-focus-lock/dist/cjs/index' {
  declare module.exports: any;
}

declare module 'react-focus-lock/dist/cjs/Lock' {
  declare module.exports: any;
}

declare module 'react-focus-lock/dist/cjs/MoveFocusInside' {
  declare module.exports: any;
}

declare module 'react-focus-lock/dist/cjs/Trap' {
  declare module.exports: any;
}

declare module 'react-focus-lock/dist/cjs/util' {
  declare module.exports: any;
}

declare module 'react-focus-lock/dist/es2015/AutoFocusInside' {
  declare module.exports: any;
}

declare module 'react-focus-lock/dist/es2015/FreeFocusInside' {
  declare module.exports: any;
}

declare module 'react-focus-lock/dist/es2015/index' {
  declare module.exports: any;
}

declare module 'react-focus-lock/dist/es2015/Lock' {
  declare module.exports: any;
}

declare module 'react-focus-lock/dist/es2015/MoveFocusInside' {
  declare module.exports: any;
}

declare module 'react-focus-lock/dist/es2015/Trap' {
  declare module.exports: any;
}

declare module 'react-focus-lock/dist/es2015/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-focus-lock/dist/cjs/AutoFocusInside.js' {
  declare module.exports: $Exports<'react-focus-lock/dist/cjs/AutoFocusInside'>;
}
declare module 'react-focus-lock/dist/cjs/FreeFocusInside.js' {
  declare module.exports: $Exports<'react-focus-lock/dist/cjs/FreeFocusInside'>;
}
declare module 'react-focus-lock/dist/cjs/index.js' {
  declare module.exports: $Exports<'react-focus-lock/dist/cjs/index'>;
}
declare module 'react-focus-lock/dist/cjs/Lock.js' {
  declare module.exports: $Exports<'react-focus-lock/dist/cjs/Lock'>;
}
declare module 'react-focus-lock/dist/cjs/MoveFocusInside.js' {
  declare module.exports: $Exports<'react-focus-lock/dist/cjs/MoveFocusInside'>;
}
declare module 'react-focus-lock/dist/cjs/Trap.js' {
  declare module.exports: $Exports<'react-focus-lock/dist/cjs/Trap'>;
}
declare module 'react-focus-lock/dist/cjs/util.js' {
  declare module.exports: $Exports<'react-focus-lock/dist/cjs/util'>;
}
declare module 'react-focus-lock/dist/es2015/AutoFocusInside.js' {
  declare module.exports: $Exports<'react-focus-lock/dist/es2015/AutoFocusInside'>;
}
declare module 'react-focus-lock/dist/es2015/FreeFocusInside.js' {
  declare module.exports: $Exports<'react-focus-lock/dist/es2015/FreeFocusInside'>;
}
declare module 'react-focus-lock/dist/es2015/index.js' {
  declare module.exports: $Exports<'react-focus-lock/dist/es2015/index'>;
}
declare module 'react-focus-lock/dist/es2015/Lock.js' {
  declare module.exports: $Exports<'react-focus-lock/dist/es2015/Lock'>;
}
declare module 'react-focus-lock/dist/es2015/MoveFocusInside.js' {
  declare module.exports: $Exports<'react-focus-lock/dist/es2015/MoveFocusInside'>;
}
declare module 'react-focus-lock/dist/es2015/Trap.js' {
  declare module.exports: $Exports<'react-focus-lock/dist/es2015/Trap'>;
}
declare module 'react-focus-lock/dist/es2015/util.js' {
  declare module.exports: $Exports<'react-focus-lock/dist/es2015/util'>;
}
