// flow-typed signature: 9fe415bf0bbabb48fa6b774e0fa28a76
// flow-typed version: <<STUB>>/react-rewards_v^1.0.7/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-rewards'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-rewards' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-rewards/build/Confetti' {
  declare module.exports: any;
}

declare module 'react-rewards/build/Emoji' {
  declare module.exports: any;
}

declare module 'react-rewards/build/index' {
  declare module.exports: any;
}

declare module 'react-rewards/build/Memphis' {
  declare module.exports: any;
}

declare module 'react-rewards/build/Reward' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-rewards/build/Confetti.js' {
  declare module.exports: $Exports<'react-rewards/build/Confetti'>;
}
declare module 'react-rewards/build/Emoji.js' {
  declare module.exports: $Exports<'react-rewards/build/Emoji'>;
}
declare module 'react-rewards/build/index.js' {
  declare module.exports: $Exports<'react-rewards/build/index'>;
}
declare module 'react-rewards/build/Memphis.js' {
  declare module.exports: $Exports<'react-rewards/build/Memphis'>;
}
declare module 'react-rewards/build/Reward.js' {
  declare module.exports: $Exports<'react-rewards/build/Reward'>;
}
