// flow-typed signature: ef6fec9644c485842a70a962120b6fa6
// flow-typed version: <<STUB>>/react-reconciler_v^0.12.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-reconciler'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-reconciler' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-reconciler/cjs/react-reconciler-persistent.development' {
  declare module.exports: any;
}

declare module 'react-reconciler/cjs/react-reconciler-persistent.production.min' {
  declare module.exports: any;
}

declare module 'react-reconciler/cjs/react-reconciler-reflection.development' {
  declare module.exports: any;
}

declare module 'react-reconciler/cjs/react-reconciler-reflection.production.min' {
  declare module.exports: any;
}

declare module 'react-reconciler/cjs/react-reconciler.development' {
  declare module.exports: any;
}

declare module 'react-reconciler/cjs/react-reconciler.production.min' {
  declare module.exports: any;
}

declare module 'react-reconciler/persistent' {
  declare module.exports: any;
}

declare module 'react-reconciler/reflection' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-reconciler/cjs/react-reconciler-persistent.development.js' {
  declare module.exports: $Exports<'react-reconciler/cjs/react-reconciler-persistent.development'>;
}
declare module 'react-reconciler/cjs/react-reconciler-persistent.production.min.js' {
  declare module.exports: $Exports<'react-reconciler/cjs/react-reconciler-persistent.production.min'>;
}
declare module 'react-reconciler/cjs/react-reconciler-reflection.development.js' {
  declare module.exports: $Exports<'react-reconciler/cjs/react-reconciler-reflection.development'>;
}
declare module 'react-reconciler/cjs/react-reconciler-reflection.production.min.js' {
  declare module.exports: $Exports<'react-reconciler/cjs/react-reconciler-reflection.production.min'>;
}
declare module 'react-reconciler/cjs/react-reconciler.development.js' {
  declare module.exports: $Exports<'react-reconciler/cjs/react-reconciler.development'>;
}
declare module 'react-reconciler/cjs/react-reconciler.production.min.js' {
  declare module.exports: $Exports<'react-reconciler/cjs/react-reconciler.production.min'>;
}
declare module 'react-reconciler/index' {
  declare module.exports: $Exports<'react-reconciler'>;
}
declare module 'react-reconciler/index.js' {
  declare module.exports: $Exports<'react-reconciler'>;
}
declare module 'react-reconciler/persistent.js' {
  declare module.exports: $Exports<'react-reconciler/persistent'>;
}
declare module 'react-reconciler/reflection.js' {
  declare module.exports: $Exports<'react-reconciler/reflection'>;
}
