// flow-typed signature: 52f9007243a0618edd81e561e3fb4961
// flow-typed version: <<STUB>>/rollup-plugin-eslint_v^5.0.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-eslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-eslint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'rollup-plugin-eslint/index' {
  declare module.exports: $Exports<'rollup-plugin-eslint'>;
}
declare module 'rollup-plugin-eslint/index.js' {
  declare module.exports: $Exports<'rollup-plugin-eslint'>;
}
